language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
   - printf "\n" | pecl install imagick

install: composer install

php:
    - 5.6
    - 7.0
    - 7.1
